# Generated by Django 5.1.7 on 2025-03-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_address_author_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='adress',
            new_name='address',
        ),
    ]
